version: '3'
volumes:
    postgres_volume:
      driver: local
services:
    postgres:
        image: postgres
        healthcheck:
          test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: Customers
        volumes:
          - ./scripts/base.sql:/docker-entrypoint-initdb.d/base.sql
          - postgres_volume:/var/lib/postgresql/data
        ports:
          - 5433:5432